### ISSUE TITLE
Jira Link, about page, Logo

### ISSUE THREAD

**Issue by schmitt-steven** [OctoPi-Team/OctoPi-Website#7]
- Link zu Jira für Endbenutzer sinnlos

- Vorschlag für about-page, Satz ändern zu: 
"Wir sind Studenten der Hochschule Mannheim und arbeiten im Rahmen des Software-Entwicklungsprojekts mit der  Sovanta AG aus Heidelberg zusammen."

- "Über Uns" zu "Über **u**ns" ändern
- Abstand der Linie über "Über uns" vergrößern

- Logo updaten

**Comment by timowenz** [comment]
Habs geändert
